version: '3'

services:
  fleetmanager:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    ports:
      - "8000:8888"
    volumes:
      - .:/fleetmanager

  db_test:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser1
      POSTGRES_PASSWORD: 932319361
