# Generated by Django 4.2 on 2023-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
