# Generated by Django 4.2 on 2023-10-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sent_at')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False, verbose_name='is_expired')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
