# Generated by Django 4.2 on 2023-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_phone_number_otpcode_car_count_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='car_count',
            field=models.PositiveIntegerField(default=0, verbose_name='car count'),
        ),
    ]
