# Generated by Django 4.2 on 2023-10-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_car_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_count',
            field=models.PositiveIntegerField(default=0, verbose_name='car count'),
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='company'),
        ),
    ]
