# Generated by Django 4.2 on 2023-10-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_car_car_count_alter_car_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'OTPCode', 'verbose_name_plural': 'OTPCodes'},
        ),
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='otpcode',
            table='OTPCode',
        ),
    ]
