# Generated by Django 4.2 on 2023-10-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_car_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_count',
        ),
    ]
