# Generated by Django 4.2 on 2023-10-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_car_car_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='car_count',
        ),
    ]
