# Generated by Django 4.2 on 2023-11-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_range', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('acceleration_range', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'metric',
                'verbose_name_plural': 'metrics',
                'db_table': 'metric',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracking.location')),
            ],
        ),
    ]
