# Generated by Django 4.2 on 2023-11-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_metric_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.location'),
        ),
    ]
