# Generated by Django 4.2 on 2023-11-09 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_car_company_alter_company_user_and_more'),
        ('tracking', '0003_alter_report_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.car', verbose_name='car_id')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
